CREATE TABLE IF NOT EXISTS OrderDetails(
    PRODUCTID INT,
    ORDERID INT,
    QUANTITY INT,
    FOREIGN KEY (PRODUCTID) REFERENCES Product(ID),
    FOREIGN KEY (ORDERID) REFERENCES OrderT(ID),
    CONSTRAINT PK_Order PRIMARY KEY (PRODUCTID, ORDERID)
);