INSERT INTO PRODUCT_CATEGORY(NAME, DESCRIPTION)
VALUES ('category 1', 'description');

INSERT INTO SUPPLIER (NAME)
VALUES ('supplier');

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, WEIGHT, CATEGORYID, SUPPLIERID, IMAGE_URL)
VALUES ('Product1', 'Description1', 197.9, 10, 1, 1, 'imageUrl1');

INSERT INTO PRODUCT (NAME, description, price, weight, CATEGORYID, SUPPLIERID, IMAGE_URL)
VALUES ('Product2', 'Description2', 587.9, 4, 1, 1, 'imageUrl2');

INSERT INTO PRODUCT (NAME, description, price, weight, CATEGORYID, SUPPLIERID, image_url)
VALUES ('Product3', 'Description3', 134.5, 3, 1, 1, 'imageUrl3');

INSERT INTO PRODUCT (NAME, description, price, weight, CATEGORYID, SUPPLIERID, image_url)
VALUES ('Product4', 'Description4', 645.2, 1, 1, 1, 'imageUrl4');

INSERT INTO LOCATION (NAME, COUNTRY, CITY, COUNTY, STREET)
VALUES ('Location1', 'Romania', 'Cluj-Napoca', 'Cluj', 'Strada Croitorilor 5');

INSERT INTO LOCATION (NAME, COUNTRY, CITY, COUNTY, STREET)
VALUES ('Location2', 'Romania', 'Brasov', 'Brasov', 'Strada Fagului 15');

INSERT INTO LOCATION (NAME, COUNTRY, CITY, COUNTY, STREET)
VALUES ('Location3', 'Romania', 'Cluj-Napoca', 'Cluj', 'Strada Observatorului 45');

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (1, 1, 222);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (2, 1, 188);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (3, 1, 33);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (1, 2, 33);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (2, 2, 2);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (3, 2, 84);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, QUANTITY)
VALUES (1, 3, 38);

INSERT INTO STOCK (PRODUCTID, LOCATIONID, quantity)
VALUES (2, 3, 10);