CREATE TABLE IF NOT EXISTS Product(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    PRICE DECIMAL,
    WEIGHT DOUBLE PRECISION,
    CATEGORYID INT,
    SUPPLIERID INT,
    IMAGE_URL VARCHAR(50),
    FOREIGN KEY (CATEGORYID) REFERENCES Product_Category(ID),
    FOREIGN KEY (SUPPLIERID) REFERENCES Supplier(ID)
);