CREATE TABLE IF NOT EXISTS Stock(

    PRODUCTID INT,
    LOCATIONID INT,
    QUANTITY INT,
    FOREIGN KEY (PRODUCTID) REFERENCES Product(ID),
    FOREIGN KEY (LOCATIONID) REFERENCES LOCATION(ID),
    CONSTRAINT PK_Stock PRIMARY KEY (PRODUCTID, LOCATIONID)
);