CREATE TABLE  IF NOT EXISTS Customer(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    EMAIL VARCHAR(50)
);